name: Dry-Run Publish to Maven Central

on:
  workflow_dispatch:

jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Deploy
        run: mvn --batch-mode clean deploy -DdryRun=true -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -P release
        env:
          CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
